algosite/urls.py
# -*- coding: utf-8 -*-

from django.contrib.auth.models import User
from bcs_client.models import StrategyBcs, AttemptBcs, Profile, AttemptResultBcs
from rest_framework import routers, serializers, viewsets, permissions
from rest_framework.decorators import detail_route, list_route
from rest_framework.response import Response

from allauth.socialaccount.providers.facebook.views import FacebookOAuth2Adapter
from rest_auth.registration.views import SocialLoginView

from allauth.exceptions import ImmediateHttpResponse
from allauth.socialaccount.adapter import DefaultSocialAccountAdapter

class FacebookLogin(SocialLoginView):
    adapter_class = FacebookOAuth2Adapter

class IsOwnerReadOnly(permissions.BasePermission):
    def has_object_permission(self, request, view, obj):
        attempt = getattr(obj, 'attempt', None)
        if attempt:
            user = obj.attempt.user
        else:
            user = obj.user
        return user == request.user

class ProfileSerializer(serializers.HyperlinkedModelSerializer):
    user = serializers.HiddenField(
        default=serializers.CurrentUserDefault()
    )

    class Meta:
        model = Profile
        read_only_fields = ('strategys', 'rating', 'user')
        # extra_kwargs = {'password': {'write_only': True},
        #                 'email': {'write_only': True}}

    # def create(self, validated_data):
    #     user = User(
    #         email=validated_data['email'],
    #         username=validated_data['username']
    #     )
    #     user.set_password(validated_data['password'])
    #     user.save()

    #     userBcsData = validated_data.pop('userBcs')
    #     UserBcs.objects.create(user=user, **userBcsData)

    #     return user

class StrategyBcsSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = StrategyBcs
        fields = ('pk', 'name', 'bAttempt', 'oAttempt', 'oTicker', 'mode', 'onlineDatetime', 'attempts')
        read_only_fields = ('bAttempt', 'oAttempt', 'oTicker', 'onlineDatetime', 'attempts')

class AttemptBcsSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = AttemptBcs
        fields = ('pk', 'strategy', 'code', 'name', 'status', 'mode', 'error_message', 'controlResult', 'numDeals', 'sumProcent', 'attemptResults')
        read_only_fields = ('status', 'error_message', 'mode', 'controlResult', 'numDeals', 'sumProcent', 'attemptResults')

    def create(self, validated_data):
        validated_data['language'] = 'python3'
        attempt = AttemptBcs.objects.create(**validated_data)
        attempt.send()
        return attempt

class AttemptResultBcsSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = AttemptResultBcs
        fields = ('ticker', 'jsonResult')
        read_only_fields = ('ticker', 'jsonResult')

class ProfileViewSet(viewsets.ModelViewSet):
    """
    *Profiles* connected with [User][Users].

    *Profile* has a *rating*.

    Order of strategys is always from last to old.

    [Users]: /rest-auth/user
    [Profiles]: /rest-api/profiles
    [attempts]: /rest-api/attempts
    [strategy]: /rest-api/strategys
    """
    queryset = Profile.objects.all()
    serializer_class = ProfileSerializer

    # def perform_create(self, serializer):
    #     UserBcs(user=serializer.save()).save()

class StrategyBcsViewSet(viewsets.ModelViewSet):
    """
    [Users][Users] create strategys.
    Strategy represents an idea of what trading algorithms can be.
    The final implementation of idea is attempt.
    Strategy accumulates [attempts][attempts] and help to navigate through attempts.

    To create strategy you only need a name. Name can be empty string.
    There are 2 modes for strategy. **O** - online and **B** - backtest.
    Strategy always created in **B** mode.
    In **B** mode user can send attempts and last attempt will update bAttempt.
    User can update strategy mode from **B** to **O**
    if he has a bAttempt with status **O**. After updating mode to **O** User can't send new attempts and change mode.
    Online strategy is tested every day on a new day and oAttempt results is updated.
    To send strategy to online User must specify oTicker from special list of tickers.

    Screen of strategy should has form for sending new attempt and show *current* attempt results.
    If strategy in backtest mode you should show bAttempt as *current* attempt,
    for online mode show oAttempt  as *current* attempt.

    Datetime is always in Moscow zone.
    Order of attempts is always from last to old.

    [Users]: /rest-auth/user
    [Profiles]: /rest-api/profiles
    [attempts]: /rest-api/attempts
    """
    serializer_class = StrategyBcsSerializer
    permission_classes = (IsOwnerReadOnly,)

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

    def get_queryset(self):
        user = self.request.user
        # if user.is_staff:
        #     return StrategyBcs.objects.all()
        return StrategyBcs.objects.filter(user=user)

class AttemptBcsViewSet(viewsets.ModelViewSet):
    """
    [Profiles][Profiles] create attempts inside [strategy][strategy].
    Attempt is an implementation of idea in a *code*.

    Every new attempt is sent to one of the backtest server where it's tested on history market data.
    It can be a long process. Attempt accumulates [attemptResults].
    Attempt can have 3 status values, **S** - sending, **O** - ok, **E** - error.
    While backtest server is testing new attempts attempt has a **S** status.
    Some *attemptResults* will appear before others, you should show all *attemptResults*.
    *attemptResult* is a row in a table of attempt. A lot of attempts will finish before the end because of programming errors. Attempt status will updated on **E**.
    In this case show *error_message* and don't show *attemptResults*. If status updated on **O**. Attempt was fully tested.

    Attempt also as strategy has mode, **O** - online and **B** - backtest.
    Attempt with status Ok has rating results. For *online* attempt results are *numDeals*, *sumProcent*
    and for *backtest* attempt results are *numDeals*, *sumProcent*, *controlResult*

    Order of attemptResult is always from old to new.

    Do post request to **/rest-api/attempts/id/send_online** to change mode to **O**

    [Profiles]: /rest-api/profiles
    [strategy]: /rest-api/strategys
    [attemptResults]: /rest-api/attemptResults
    """
    serializer_class = AttemptBcsSerializer
    permission_classes = (IsOwnerReadOnly,)

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

    def get_queryset(self):
        user = self.request.user
        # if user.is_staff:
        #     return AttemptBcs.objects.all()
        return AttemptBcs.objects.filter(user=user)

    @detail_route(methods=['get'], permission_classes=[IsOwnerReadOnly])
    def send_online(self, request, pk=None):
        attempt = AttemptBcs.objects.get(pk=pk)
        if request.user.id != attempt.user.id:
            return Response({'result': 'error', 'error_message': 'User must be owner of the attempt'}, status=403)

        if attempt.status == 'O':
            attempt.sendOnline()
            return Response({'result': 'ok', 'error_message': ''})
        else:
            return Response({'result': 'error', 'error_message': 'Попытка должна иметь статус OK'})

class AttemptResultBcsViewSet(viewsets.ReadOnlyModelViewSet):
    """
    *AttemptResult* is only for reading.
    *AttemptResult* has *ticker*. Ticker is a name of market instrument.
    *AttemptResult* has jsonResult. This field is not fixed. The keys can change in a future.

    [Profiles]: /rest-api/profiles
    [strategy]: /rest-api/strategys
    [attemptResults]: /rest-api/attemptResults
    """

    serializer_class = AttemptResultBcsSerializer
    permission_classes = (IsOwnerReadOnly,)

    def get_queryset(self):
        user = self.request.user
        if user.is_staff:
            return AttemptResultBcs.objects.all()
        return AttemptResultBcs.objects.filter(attempt__user=user)


router = routers.DefaultRouter(schema_title='Quantforces API')
router.register(r'profiles', ProfileViewSet, 'profile')
router.register(r'strategys', StrategyBcsViewSet, 'strategybcs')
router.register(r'attempts', AttemptBcsViewSet, 'attemptbcs')
router.register(r'attemptResults', AttemptResultBcsViewSet, 'attemptresultbcs')

###############################################################################################
from django.conf.urls import patterns, url, include
from django.contrib import admin
from allauth.account.views import ConfirmEmailView

admin.autodiscover()

urlpatterns = patterns(
    '',
    # url(r'^', include('staticpage.urls', namespace="staticpage")),
    # url(r'^sandbox/', include('sandbox.urls', namespace="sandbox")),
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^accounts/', include('my_registration.backends.default.urls')), # django-registration
    # url(r'^contest/', include('contest.urls', namespace="contest")),
    # url(r'^attempt/', include('attempt.urls', namespace="attempt")),
    # url(r'^blog/', include('blog.urls', namespace="blog")),
    # url(r'^i18n/', include('django.conf.urls.i18n')),
    # url(r'^data_upload/', include('data_upload.urls', namespace="data_upload")),
    url(r'^', include('bcs_client.urls', namespace="bcs_client")),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/profile/', include('user_profile.urls')),

    # url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # url(r'^rest-api/', include(router.urls)),
    url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^rest-auth/registration/account-confirm-email/(?P<key>[-:\w]+)/$',
        ConfirmEmailView.as_view(), name="account_confirm_email"),
    url(r'^rest-auth/registration/', include('rest_auth.registration.urls')),

attempt/urls.py
from django.conf.urls import patterns, url
import views

urlpatterns = patterns(
    '',
    url(r'^(?P<attempt_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<attempt_id>[0-9]+)/data$', views.data, name='data'),
)

bcs_client/urls.py
from django.conf.urls import patterns, url, include
import views
import os
import json
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^profile/$', views.profile, name='profile'),

    url(r'^rating/$', views.rating, name='rating'),
    url(r'^attempt/$', views.showAttempts, name='showAttempts'),
    url(r'^send_algo/$', views.sendAlgo, name='sendAlgo'),
    url(r'^send/$', views.getForm, name='getForm'),
    url(r'^main/$', views.getMain, name='getMain'),
    url(r'^landing/$', views.getLanding, name='getLanding'),

    url(r'^doc/$', views.getDocMain, name='getDocMain'),
    url(r'^doc/(?P<docName>[\w-]+)/$', views.getDoc, name='getDoc'),
    url(r'^doc/z7Ganc864/compile/$', views.compileDoc, name='compileDoc'),

    url(r'^attempt/(?P<attempt_id>[0-9]+)/info/$', views.getAttemptInfo, name='getAttemptInfo'),
    url(r'^attempt/(?P<attempt_id>[0-9]+)/$', views.getAttempt, name='getAttempt'),
    url(r'^attempt/(?P<attempt_id>[0-9]+)/chart/', include('tradingview.urls', namespace='tradingview')),

    url(r'^attempt/bcs_nfe76Rtfs2vk/$', views.getAttemptWithoutLogin, name='getAttemptWithoutLogin'),
    url(r'^attempt/delete/(?P<attempt_id>[0-9]+)/$', views.deleteAttempt, name='deleteAttempt'),
    url(r'^attempt/add_online/$', views.addOnline, name='addOnline'),

    url(r'^add_email/$', views.add_email, name='add_email'),

    url(r'^$', views.index_main, name='index'),

    url(r'^team/$', TemplateView.as_view(template_name='bcs_client/team.html'), name='team'),
    url(r'^agreement/$', TemplateView.as_view(template_name='bcs_client/agreement.html'), name='agreement'),
]

blog/urls.py
from django.conf.urls import patterns, url
import views

urlpatterns = patterns(
    '',
    url(r'^(?P<article_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^$', views.index, name='index'),
    # url(r'^(?P<attempt_id>[0-9]+)/data$', views.data, name='data'),
)

bcs_client/forms.py
from django import forms
from bcs_client.models import Profile

class SignupForm(forms.Form):
    first_name = forms.CharField(max_length=100, required=True)
    # rules = forms.BooleanField(required=True)
    # last_name = forms.CharField(max_length=30, label='Achternaam')

    def signup(self, request, user):
        user.first_name = self.cleaned_data['first_name']
        user.save()
        Profile(user=user, first_name=user.first_name).save()

attempt/views.py
#!/usr/bin/python
#coding=utf-8

from django.shortcuts import render
from django.shortcuts import get_object_or_404
from models import Attempt, listBuySell
import json
from django.http import HttpResponse

def detail(request, attempt_id):
    attempt = get_object_or_404(Attempt, pk=attempt_id)
    context = {
        'buy_sell': listBuySell.objects.filter(attempt__id=attempt_id),
        'attempt': attempt,
    }
    return render(request, 'attempt/detail.html', context)

def data(request, attempt_id):
    attempt = get_object_or_404(Attempt, pk=attempt_id)
    # orders = attempt.getListEvents()
    priceData = attempt.market_data.getPriceData('open')
    # priceData.append(priceData[-1]) # Добавляем доп день
    # balance_list = attempt.getListBalance()
    jsonDict = {"price": priceData,
                "portfolio": attempt.result_open.portfolio,
                # "title_events": ("order", "number", "quantity"),
                # "events": orders,
                # "title_balance": ("number", "money", "stock"),
                # "balance": balance_list,
               }
    return HttpResponse(json.dumps(jsonDict), content_type="application/json")

templates/bcs_client/agreement.html
{% extends "bcs_client/menu.html" %}
{% load staticfiles %}

{% block head %}
{% endblock %}

{% block title %}
  Пользовательское соглашение
{% endblock %}

{% block content %}
  <div class="l-container">
    <div class="row">
      <div class="col s12">
        <div class="title -inner">Пользовательское соглашение</div>
      </div>
      <div class="row">
        В разработке
      </div>
    </div>
  </div>
{% endblock %}

templates/bcs_client/base.html
{% extends "base.html" %}

{% load staticfiles %}

{% block header %}
  <div class="l-container">
    <div class="row">
      <div class="col s4 header__logo-wrapper">
        <a href="{% url 'bcs_client:getMain' %}" class="header__logo h-center"><img src="{% static 'bcs_client/images/logo.png' %}"></a>
        <div class="header__logo-text h-bold">BCS Quants
          <br/>Challenge</div>
      </div>
      {% block header_action %}{% endblock %}
    </div>
  </div>
{% endblock %}

{% block footer %}
  <div class="l-container">
    <div style="margin-bottom: 0;" class="row">
      <div class="col s8 h-muted" style="line-height: 20px; margin-top: 10px">© 2017 BCS Global Markets </br> ООО "Компания БКС", лицензия №154-04434-100000 от 10.01.2001 на осуществление брокерской деятельности</div>
      <div class="col s3"><span class="h-muted">Поддержка&nbsp;—&nbsp;</span><a href="mailto:support@bcsquants.com" class="h-link">support@bcsquants.com</a></div>
      <div class="col s1"><a href="http://www.bcsquants.com" class="h-link">www.bcsquants.com</a></div>
    </div>
  </div>
{% endblock %}

templates/bcs_client/doc.html
{% extends "bcs_client/menu.html" %}
{% load staticfiles %}

{% block head %}
  <script type="text/javascript" src="//vk.com/js/api/openapi.js?136"></script>
  <link rel="stylesheet" href="{% static 'bcs_client/gitbook-markdown.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.8.0/styles/monokai-sublime.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.8.0/highlight.min.js"></script>
  <script>
    hljs.initHighlightingOnLoad();
  </script>
  <style>
    h1, h2, h3, h4, h5, h6 {
      color: #de0020;
    }
    ol li {
      list-style-type: decimal;
    }
    ul li {
      list-style-type: initial;
    }
  </style>
{% endblock %}

{% block title %}
  Документация
{% endblock %}

{% block content %}
  <div class="l-container">
    <div class="row">
      <div class="col s3">
        <div class="left-menu">
          {% for item in menu %}
            <a href="{% url 'bcs_client:getDoc' item.1 %}" class="left-menu__item {% if item.1 == docName %} -active {% endif %} h-link">{{ item.0 }}</a>
          {% endfor %}
        </div>
      </div>
      <div class="col s9 wiki__content-wrapper" style="overflow: hidden;">
        <div class="wiki__content">

          <!-- <div class="title -inner">Как создать стратегию</div> -->
          <!--<p><span class="h-bold">У вас еще нет ни одной стратегии, работающей на онлайн данных.</span>Перевести стратегию в онлайн можно на странице результатов стратегии.</p>
          <div class="editor"><img src="/images/editor.jpg"></div>
          <div class="title -inner">Стратегия</div>
          <p>У вас еще нет ни одной стратегии, работающей на онлайн данных. Перевести стратегию в онлайн можно на странице результатов стратегии.</p>
          <div class="editor"><img src="/images/editor.jpg"></div>
          <p>Функция int вызывается один раз для каждого инструмента, ей передается пустой класс. Далее на каждую секунду биржевой информации вызывается функция tick, ей передается тот же класс self и data — вся доступная на данный момент времени информация.</p> -->

          <article class="gitbook-markdown-body">{% autoescape off %}{{ content }}{% endautoescape %}</article>

        </div>
      </div>
    </div>
  </div>
  {% include "bcs_client/vk.html" %}
{% endblock %}

templates/bcs_client/form.html
{% extends "bcs_client/menu.html" %}
{% load staticfiles %}

{% block title %}
  Создание стратегии
{% endblock %}

{% block head %}
  <link rel="stylesheet" href="{% static 'sandbox/codemirror/codemirror.css' %}">
  <link rel="stylesheet" href="{% static 'sandbox/codemirror/monokai.css' %}">
  <link rel="stylesheet" href="{% static 'sandbox/codemirror/addon/foldgutter.css' %}">
  <link rel="stylesheet" href="{% static 'sandbox/codemirror/addon/dialog.css' %}">
  <link rel="stylesheet" href="{% static 'sandbox/codemirror/addon/show-hint.css' %}">
  <script src="{% static 'sandbox/codemirror/codemirror.js' %}"></script>
  <script src="{% static 'sandbox/codemirror/matchbrackets.js' %}"></script>
  <script src="{% static 'sandbox/codemirror/python.js' %}"></script>
  <script src="{% static 'sandbox/codemirror/sublime.js' %}"></script>
  <script src="{% static 'sandbox/codemirror/addon/searchcursor.js' %}"></script>
  <script src="{% static 'sandbox/codemirror/addon/search.js' %}"></script>
  <script src="{% static 'sandbox/codemirror/addon/dialog.js' %}"></script>
  <script src="{% static 'sandbox/codemirror/addon/closebrackets.js' %}"></script>
  <script src="{% static 'sandbox/codemirror/addon/comment.js' %}"></script>
  <script src="{% static 'sandbox/codemirror/addon/hardwrap.js' %}"></script>
  <script src="{% static 'sandbox/codemirror/addon/foldcode.js' %}"></script>
  <script src="{% static 'sandbox/codemirror/addon/foldgutter.js' %}"></script>
  <script src="{% static 'sandbox/codemirror/addon/brace-fold.js' %}"></script>
  <script src="{% static 'sandbox/codemirror/addon/indent-fold.js' %}"></script>
  <style type="text/css">.CodeMirror {
    border-top: 1px solid black;
    border-bottom: 1px solid black;
    border-right: 1px solid black;
    border-left: 1px solid black;
    height: 490px;
    font-size: 11pt;
  }
  </style>
{% endblock %}

{% block content %}
  <div class="l-container">
    <div class="row">
      <div class="col s12">
        <div class="title -inner">Создание стратегии</div>
      </div>
    </div>
    <form id="form_code" action="{% url 'bcs_client:sendAlgo' %}" method="post">
      {% csrf_token %}
      <div class="row">
        <div class="input-field col s5">
          <input type="text" id="name" name="name" value="{{name}}">
          <label for="name">Название стратегии</label>
        </div>
      </div>
      <input type="hidden" id="language" name="language" value="python3">
      <div class="row editor">
        <div class="col s12">
          <textarea id="code" name="code" rows="40">{{ code }}</textarea>
        </div>
      </div>
      {% if error_message %}
        <div class="row">
          <div class="col s12">
            <div class="error-trace">
              <div class="error-trace__title">Чтобы перейти к результатам, устраните ошибки ниже:</div>
              <div class="error-trace__text">{{ error_message|linebreaks }}</div>
            </div>
          </div>
        </div>
      {% endif %}
      <div class="row">
        <div class="col s12 h-text-right"><button id="btn_code" type="submit" class="btn btn-default">Отправить стратегию</button></div>
      </div>
    </form>
  </div>

  <script type="text/javascript">
    var editor = CodeMirror.fromTextArea(document.getElementById("code"), {
        mode: {
          name: "python",
          singleLineStringErrors: false
        },
        lineNumbers: true,
        indentUnit: 4,
        matchBrackets: true,
        keyMap: 'sublime',
        theme: "monokai",
        autoCloseBrackets: true,
        showCursorWhenSelecting: true,

        foldGutter: true,
        gutters: ["CodeMirror-linenumbers", "CodeMirror-foldgutter"],
        lineWrapping: true,
    });

    editor.addKeyMap({
        "Tab": function (cm) {
            if (cm.somethingSelected()) {
                var sel = editor.getSelection("\n");
                // Indent only if there are multiple lines selected, or if the selection spans a full line
                if (sel.length > 0 && (sel.indexOf("\n") > -1 || sel.length === cm.getLine(cm.getCursor().line).length)) {
                    cm.indentSelection("add");
                    return;
                }
            }

            if (cm.options.indentWithTabs)
                cm.execCommand("insertTab");
            else
                cm.execCommand("insertSoftTab");
        },
        "Shift-Tab": function (cm) {
            cm.indentSelection("subtract");
        }
    });
  </script>

{% endblock %}

templates/bcs_client/menu.html
{% extends "bcs_client/base.html" %}

{% load staticfiles %}

{% block header_action %}
  <div class="col s8 h-text-right">
    <nav class="menu">
      <a href="{% url 'bcs_client:getForm' %}" class="menu__item {% if keyPage == 'getForm' %}-selected{% endif %}">
        <span class="menu__item-text -plus">Создать стратегию</span>
      </a>
      <a href="{% url 'bcs_client:showAttempts' %}" class="menu__item {% if keyPage == 'showAttempts' %}-selected{% endif %}">
        <span class="menu__item-text">Мои стратегии{% if request.user.profile.numberOnlineAttempts %}<span class="menu__item-helper">{{ request.user.profile.numberOnlineAttempts }}</span></span>{% endif %}</a>
      <a href="{% url 'bcs_client:rating' %}" class="menu__item {% if keyPage == 'rating' %}-selected{% endif %}">
        <span class="menu__item-text">Рейтинг</span>
      </a>
      <a href="{% url 'bcs_client:getDocMain' %}" class="menu__item {% if keyPage == 'doc' %}-selected{% endif %}">
        <span class="menu__item-text">Информация</span>
      </a>
      <a href="{% url 'bcs_client:profile' %}" class="menu__item {% if keyPage == 'profile' %}-selected{% endif %}">
        <svg height="50px" class="menu__account-icon">
          <use xlink:href="#account"></use>
        </svg>
      </a>
    </nav>
  </div>
{% endblock %}

templates/bcs_client/rating.html
{% extends "bcs_client/menu.html" %}
{% load staticfiles %}

{% block title %}
  Рейтинг
{% endblock %}

{% block head %}
  <script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
  <link href="{% static 'staticpage/css/table.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
  <script>
    $(document).ready(function() {
      $.fn.dataTable.ext.errMode = 'none';
      options = {
        "ajax": "{% url 'bcs_client:rating' %}?json=1",
        "order": [],
        "lengthChange": false,
        "searching": false,
        "info": false,
        "pagingType": "numbers",
      }
      var table = $('#rating_table').DataTable(options);
      table.page.len(50);
    });
  </script>

  <div class="l-container">
    <div class="row">
      <div class="col s12">
        <div class="title -inner">Рейтинг</div>
        {% if userResult.2 == 0 %}
          <div style="font-size: 20px;color: red;">
            У вас нет ни одной стратегии в онлайн, поэтому ваш рейтинг нулевой
          </div>
        {% endif %}
        <div class="subtitle">Ваша позиция</div>
        <table class="c-table">
          <thead>
            <tr>
              {% for key in tableKey %}
                <th>{{ key }}</th>
              {% endfor %}
            </tr>
          </thead>
          <tbody>
            <tr class="-selected">
              {% if userResult %}
                <td>{{ userResult.0 }}</td>
                <td>{{ userResult.1 }} {% if not userProfile.cv %}. Не забудьте <span style="font-weight: bold;"><a href="{% url 'bcs_client:profile' %}">загрузить резюме</a></span> в личном кабинете!{% endif %}</td>
                <td class="h-muted">{{ userResult.2 }}</td>
                <td class="h-muted">{{ userResult.3 }}</td>
                <td class="h-muted">{{ userResult.4 }}</td>
              {% else %}
                <td>Кажется вы ещё не участвуете в соревновании, <a href="{% url 'account_login' %}">авторизуйтесь</a> или <a href="{% url 'account_signup' %}">зарегистрируйтесь</a>. Не забудьте <span style="font-weight: bold;">загрузить резюме</span> в личном кабинете!</td>
              {% endif %}
            </tr>
          </tbody>
        </table>
        <div class="subtitle">Все участники</div>

        <table id="rating_table" class="" cellspacing="0" width="100%" >
          <thead>
            <tr>
              {% for col in tableKey %}
                <th>{{ col }}</th>
              {% endfor %}
            </tr>
          </thead>
          <tfoot>
            <tr>
              {% for col in tableKey %}
                <th>{{ col }}</th>
              {% endfor %}
            </tr>
          </tfoot>
        </table>

        <!-- <table class="c-table">
          <thead>
            <thead>
              <tr>
                <th>Место</th>
                <th>Участник</th>
                <th>Всего стратегий</th>
                <th>Рейтинг по контрольной выборке</th>
                <th>Рейтинг по онлайн стратегиям</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>9</td>
                <td>Иван Иванов</td>
                <td class="h-muted">198</td>
                <td class="h-muted">2</td>
                <td class="h-muted">4</td>
              </tr>
              <tr class="-selected">
                <td>9</td>
                <td>Иван Иванов</td>
                <td class="h-muted">198</td>
                <td class="h-muted">2</td>
                <td class="h-muted">4</td>
              </tr>
              <tr>
                <td>9</td>
                <td>Иван Иванов</td>
                <td class="h-muted">198</td>
                <td class="h-muted">2</td>
                <td class="h-muted">4</td>
              </tr>
              <tr>
                <td>9</td>
                <td>Иван Иванов</td>
                <td class="h-muted">198</td>
                <td class="h-muted">2</td>
                <td class="h-muted">4</td>
              </tr>
            </tbody>
          </thead>
        </table> -->

      </div>
    </div>
  </div>
{% endblock %}

templates/bcs_client/vk.html
<!-- VK Widget -->
<div id="vk_community_messages"></div>
<script type="text/javascript">
    VK.Widgets.CommunityMessages("vk_community_messages", 131749987, {
      // onCanNotWrite: function() {
      //   VK.Widgets.CommunityMessages.destroy("vk_community_messages");
      // }
    });
</script>